### ISSUE TITLE
Consider a Rust port

### ISSUE THREAD

**Issue by rnewman** [kitcambridge/ecec#16]
This is a good place for a safe and expressive systems language, and would also provide some opportunities for learning about shipping Rust on iOS.

**Comment by ghost** [comment]
I see https://github.com/sfackler/rust-openssl supports OpenSSL 1.1.0, so that's exciting! It also looks like it can dynamically link against OpenSSL, which I assume we'd want for iOS.

**Comment by ghost** [comment]
I started on a Rust binding here: https://github.com/kitcambridge/ecers
